# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 芝嫲视频

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # UTC时间 +8 北京
  watch:
    types: started
  repository_dispatch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          git checkout main
          npm install
      - name: '运行 【芝嫲视频】'
        run: |
          node zhima.js
        env:
          TZ: Asia/shanghai
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          ZM_zhimabody: ${{ secrets.ZM_zhimabody }}
